# Returns all columns from scraped data with defined dtype
def get_dtypes():
    return {
        '0 to 62 mph (secs)': 'float64',
        'CO2 (g/km)': 'float64',
        'Camshaft': 'unicode',
        'Cylinder Layout': 'unicode',
        'Cylinders': 'float64',
        'EC Combined (mpg)': 'float64',
        'EC Extra Urban (mpg)': 'float64',
        'EC Urban (mpg)': 'float64',
        'Engine Layout': 'unicode',
        'Engine Power - BHP': 'float64',
        'Engine Torque - LBS.FT': 'float64',
        'Engine Torque - NM': 'float64',
        'Fuel Delivery': 'unicode',
        'Fuel Tank Capacity (Litres)': 'float64',
        'Gears': 'unicode',
        'Gross Vehicle Weight': 'float64',
        'Height': 'float64',
        'Height (including roof rails)': 'float64',
        'Insurance Group 1': 'unicode',
        'Insurance Group 1 - 50 Effective January 07': 'unicode',
        'Length': 'float64',
        'Luggage Capacity (Seats Down)': 'float64',
        'Luggage Capacity (Seats Up)': 'float64',
        'Manufacturers Corrosion Perforation Guarantee - Years': 'float64',
        'Manufacturers Paintwork Guarantee - Years': 'float64',
        'Max. Loading Weight': 'float64',
        'Max. Roof Load': 'float64',
        'Max. Towing Weight - Braked': 'float64',
        'Max. Towing Weight - Unbraked': 'float64',
        'Minimum Kerbweight': 'float64',
        'NCAP Adult Occupant Protection %': 'float64',
        'NCAP Child Occupant Protection %': 'float64',
        'NCAP Overall Rating - Effective February 09': 'unicode',
        'NCAP Pedestrian Protection %': 'float64',
        'No. of Seats': 'float64',
        'Service Interval Frequency - Months': 'float64',
        'Service Interval Mileage': 'float64',
        'Standard manufacturers warranty - Mileage': 'float64',
        'Standard manufacturers warranty - Years': 'float64',
        'Top Speed': 'float64',
        'Transmission': 'unicode',
        'Turning Circle - Kerb to Kerb': 'float64',
        'Wheel Style': 'unicode',
        'Wheel Type': 'unicode',
        'Wheelbase': 'float64',
        'Width': 'float64',
        'Width (including mirrors)': 'float64',
        'dealer_id': 'unicode',
        'dealer_name': 'unicode',
        'ga_account': 'unicode',
        'page_name': 'unicode',
        'page_type': 'unicode',
        'site_section': 'unicode',
        'vehicle_access_index': 'int64',
        'vehicle_access_method': 'unicode',
        'vehicle_body_style': 'unicode',
        'vehicle_colour': 'unicode',
        'vehicle_fuel_type': 'unicode',
        'vehicle_group_id': 'unicode',
        'vehicle_id': 'int64',
        'vehicle_make': 'unicode',
        'vehicle_model': 'unicode',
        'vehicle_postcode': 'unicode',
        'vehicle_price': 'int64',
        'vehicle_title': 'unicode',
        'vehicle_transmission': 'unicode',
        'vehicle_trim': 'unicode',
        'vehicle_year': 'int64'
        }

# Returns columns names of columns we'll be doing analysis on. Comment out where necessary.    
def get_main_columns():
    return [
        '0 to 62 mph (secs)',
        'CO2 (g/km)',
        'Camshaft',
        'Cylinder Layout',
        'Cylinders',
        'EC Combined (mpg)',
        'EC Extra Urban (mpg)',
        'EC Urban (mpg)',
        'Engine Layout',
        'Engine Power - BHP',
        'Engine Torque - LBS.FT',
        'Engine Torque - NM',
        'Fuel Delivery',
        'Fuel Tank Capacity (Litres)',
        'Gears',
        'Gross Vehicle Weight',
        'Height',
        'Height (including roof rails)',
        'Insurance Group 1',
        'Insurance Group 1 - 50 Effective January 07',
        'Length',
        'Luggage Capacity (Seats Down)',
        'Luggage Capacity (Seats Up)',
        'Manufacturers Corrosion Perforation Guarantee - Years',
        'Manufacturers Paintwork Guarantee - Years',
        'Max. Loading Weight',
        'Max. Roof Load',
        'Max. Towing Weight - Braked',
        'Max. Towing Weight - Unbraked',
        'Minimum Kerbweight',
        'NCAP Adult Occupant Protection %',
        'NCAP Child Occupant Protection %',
        'NCAP Overall Rating - Effective February 09',
        'NCAP Pedestrian Protection %',
        'No. of Seats',
        'Service Interval Frequency - Months',
        'Service Interval Mileage',
        'Standard manufacturers warranty - Mileage',
        'Standard manufacturers warranty - Years',
        'Top Speed',
        'Transmission',
        'Turning Circle - Kerb to Kerb',
        'Wheel Style',
        'Wheel Type',
        'Wheelbase',
        'Width',
        'Width (including mirrors)',
        'dealer_id',
        'dealer_name',
        'ga_account',
        'page_name',
        'page_type',
        'site_section',
        'vehicle_access_index',
        'vehicle_access_method',
        'vehicle_body_style',
        'vehicle_colour',
        'vehicle_fuel_type',
        'vehicle_group_id',
        'vehicle_id',
        'vehicle_make',
        'vehicle_model',
        'vehicle_postcode',
        'vehicle_price',
        'vehicle_title',
        'vehicle_transmission',
        'vehicle_trim',
        'vehicle_year',
        ]
    
    
    
    
    